# Generated by Django 3.0.7 on 2022-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='order',
            field=models.IntegerField(auto_created=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='imagesrc',
            field=models.ImageField(upload_to='gallery-images'),
        ),
    ]
