# Generated by Django 3.0.7 on 2022-08-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20220802_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.IntegerField(),
        ),
    ]
