# Generated by Django 3.0.7 on 2022-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdetail',
            name='image',
            field=models.ImageField(upload_to='about-images'),
        ),
    ]
